name: Docs Push

on:
  push:
    branches: [ '**' ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

env:
  DISABLE_MKDOCS_2_WARNING: true

jobs:
  deploy:
    if: hashFiles('docs/requirements.txt') != ''
    continue-on-error: true
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
        working-directory: docs
      - run: mkdocs build --verbose
        working-directory: docs
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: 'site'
      - uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
